trigger:
- master

variables:
  version: 3.1

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: 'build'
    projects: 'Epoch.net/*.csproj'
    arguments: '-p:Version=$(version)'
- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: 'test'
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    testRunTitle: 'Run Tests'
- task: DotNetCoreCLI@2
  displayName: Create nuget package
  inputs:
    command: 'pack'
    packagesToPack: 'Epoch.net/*.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'